{% set name = "langdetect" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 363795ea005f1243c958e953245dac5d814fabdc025c9afa91588c5fa6b2fa83

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - six

test:
  imports:
    - langdetect
    - langdetect.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Mimino666/langdetect
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Language detection library ported from Google's language-detection.
  doc_url: https://github.com/Mimino666/langdetect
  dev_url: https://github.com/Mimino666/langdetect

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
