{% set name = "langdetect" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # standard pypi url for 1.0.7 is missing
  url: https://files.pythonhosted.org/packages/59/59/4bc44158a767a6d66de18c4136c8aa90491d56cc951c10b74dd1e13213c9/langdetect-1.0.7.zip
  sha256: cbc1fef89f8d062739774bd51eda3da3274006b3661d199c2655f6b3f6d605a0

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - six

test:
  imports:
    - langdetect
    - langdetect.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Mimino666/langdetect
  summary: Language detection library ported from Google's language-detection.
  description: Port of Nakatani Shuyo's language-detection library (version from 03/03/2014) to Python.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/Mimino666/langdetect
  dev_url: https://github.com/Mimino666/langdetect

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
