{% set name = "langdetect" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cbc1fef89f8d062739774bd51eda3da3274006b3661d199c2655f6b3f6d605a0

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - langdetect
    - langdetect.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Mimino666/langdetect
  summary: Language detection library ported from Google's language-detection.
  description: Port of Nakatani Shuyo's language-detection library (version from 03/03/2014) to Python.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/Mimino666/langdetect
  dev_url: https://github.com/Mimino666/langdetect

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
