{% set name = "langdetect" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 363795ea005f1243c958e953245dac5d814fabdc025c9afa91588c5fa6b2fa83

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six

test:
  imports:
    - langdetect
    - langdetect.tests
    - langdetect.utils

about:
  home: https://github.com/Mimino666/langdetect
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: "Language detection library ported from Google's language-detection."
  doc_url: https://github.com/Mimino666/langdetect
  dev_url: https://github.com/Mimino666/langdetect

extra:
  recipe-maintainers:
    - pmlandwehr
