travis:
  secure:
    BINSTAR_TOKEN: j9Xfu60dwisXMBuaS5s49mGmAfdygk7cvEg6Ml6g/EhdOn6HBbRnN2T7gyzvyO8TPecWY04K0PgKkui/gW5LGbU9+7f9AqBqRf21RFUe5FQe0SJGH5pta2rbtA2v4cRcWtPb/UEdTMQoxTI86U/TLmqaPZOZ6mS0/Z1HHytCOvXofGWUsOuEpJWplHdgHi6CYV+wgpSAKGUxXsIo/favK3kJpBUsBrF5wMDtKow2i9JJXxkvbrWGAjMqfIZqPjPpecVgmKwvbykHV/6pqoIdqoeL8NSXkm4BMx4Bdx3lbhzjHLunZaKwIYOoJfTLtTHg6VsJg1l7G4W+rCtPJTzZTnFtkC/n7fV3PPewdtTJmBiF9hyEXwfG96G72HPzGy2ks+SpBFqsWB8M2B6ti/u1lMLXoy7HGOZP0jT7RajVeXAPf+bfHbAjwq9Hf1L7TCpfMISQ7jATLRyDqleEOHGN2fG0xMWBsq580anT/vp0MjgINipi5pjvVCGGIO0CU8lcU/QbmBZQHFE41NoDNMCDxXCugM8F8gQ+r6eranf0Zurjfzl9nCrjZTpg2aOmaSnnRTnssUfjg+YbhCofoh1JJ4//z5n0H7suaqOVHrH3YFe+0+2V7baCe0JYA7NUK+JWMcOJLFlE5bC1+o39Irh8+BFhmTt+nOsJR0I/j9hqWJg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
