travis:
  secure:
    BINSTAR_TOKEN: tBBCl6jWQvNcF0PdaIH8pEAuH80qttETeB7RKU5Ev0QZFMVgZ/kSo9Qpy8VfvWV3iC80MppC8bdemQ1e55fOgv+o9xauJFjiGMPAndCEwsZ0IYjXIjTaLWldrBeGaMFRBeq9pJDU67LcjII86iXk3hzcgT6TDvIZ0vT3HVny4bifzmA6KkWST95obVsfuMFBx9vpdNLreoza0PbcEk6oTIGLIOuO/jsbhj2dqxADWD46+kGAaJtG6ssxGImd6u5/AYftNkXHysMPkPYIFoXMiyov2gCYaNvRng7/ZpwrKIBiePP4z9cyq4+fL86HUctoitU7Tt14oOVDlxIKJbBc9X+cUmD2jomx3r5i7T38om65ZyJWFHUuIBmzP3ScImscrvwcmMNRiEG47plVljUS/g0Tvv5Yf/QsTsbjXpynFwhgrEWO2EnNfYKHCPo4fSFkpCsyibxkjKI3c4VG2Sw4ejkRqCTfumef2cyp4BXuSIF2bku36ypqjqvd6ii1De5uY8sHbxablZ3s4bF0e3YIuP0fAATvRB2U6sGA6+32vkfErx2zgMEwow3qkcsjJGsEx07QsvmNf4FoA27rUoxYDNw1XpizVSYXqpz5pCk9qeDBpMsA7W1y645WYINq3K0JCEp9CL7TSTHpxxE8qNSvl6rHZ73N6NmBrXwZKOEAzB0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
